name: Actions Workflow

on: 
  schedule:
    - cron: "*/5 * * * *"
  #push:
  #pull_request:
   #types: [closed, assigned, opened, reopened]
  
jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps: 
      - name: List Files
        run: |
          pwd
          ls
      - name: Get repository
        uses: action/checkout@v1
      - name: List Files after checkout
        run: |
          pwd
          ls -a

