name: Docker container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alphine3.10
      # env:
      # volumes:
      # options: --cpus 1 --host
        
    steps:
      - name: Log Node Version
        run: |
          node -v
          cat /etc/os-release
  