name: Matrix

on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        node_version: [6,8,10]
        exclude: 
          - os: ubuntu-latest
            node_version: 8
          - os: macos-latest
            node_version: 10
      fail-fast: true
      # max-parallel: 0
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log Version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log Version after setup node
        run: node -v